In [1]:
import numpy as np

In [3]:
def rotation_matrix_from_vectors(vec1, vec2):
    """ Find the rotation matrix that aligns vec1 to vec2
    :param vec1: A 3d "source" vector
    :param vec2: A 3d "destination" vector
    :return mat: A transform matrix (3x3) which when applied to vec1, aligns it with vec2.
    """
    a, b = (vec1 / np.linalg.norm(vec1)).reshape(3), (vec2 / np.linalg.norm(vec2)).reshape(3)
    v = np.cross(a, b)
    c = np.dot(a, b)
    s = np.linalg.norm(v)
    kmat = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    rotation_matrix = np.eye(3) + kmat + kmat.dot(kmat) * ((1 - c) / (s ** 2))
    return rotation_matrix

v1 = np.array([0, 1, 0])
v1 = v1/np.linalg.norm(v1)

v2 = np.array([0, 0, 1])
v2 = v2/np.linalg.norm(v2)

In [4]:
R = rotation_matrix_from_vectors(v1, v2)

In [5]:
v1, v2, R@v1

(array([0., 1., 0.]), array([0., 0., 1.]), array([0., 0., 1.]))

In [12]:
vec1 = np.array([1, 0, 0])
vec2 = np.array([-1, 0, 0])
np.rad2deg(angle_between(vec1, v2))

180.0

In [13]:
vec1, -vec1

(array([1, 0, 0]), array([-1,  0,  0]))

In [15]:
a = np.array(
[[-0.3954264 ,-0.06010875 ,0.54459697],
 [-0.3954264 , 0.6355572  ,0.54459697],
 [ 0.30143332, 0.6355572  ,0.54459697],
 [ 0.30143332,-0.06010875 ,0.54459697],
 [-0.3954264 ,-0.06010875 ,2.2854116 ],
 [-0.3954264 , 0.6355572  ,2.2854116 ],
 [ 0.30143332, 0.6355572  ,2.2854116 ],
 [ 0.30143332,-0.06010875 ,2.2854116 ]]
)

a

array([[-0.3954264 , -0.06010875,  0.54459697],
       [-0.3954264 ,  0.6355572 ,  0.54459697],
       [ 0.30143332,  0.6355572 ,  0.54459697],
       [ 0.30143332, -0.06010875,  0.54459697],
       [-0.3954264 , -0.06010875,  2.2854116 ],
       [-0.3954264 ,  0.6355572 ,  2.2854116 ],
       [ 0.30143332,  0.6355572 ,  2.2854116 ],
       [ 0.30143332, -0.06010875,  2.2854116 ]])

In [20]:
maxs = np.max(a, axis=0)

maxs

array([0.30143332, 0.6355572 , 2.2854116 ])

In [26]:
ind = np.zeros((2, 2, 2))
# ind[np.equal(a, maxs)] = list(range(8))
# ind, np.equal(a, maxs)
bools = np.equal(a, maxs)
for i, (xb,yb,zb) in enumerate(bools.astype(int)):
    ind[xb, yb, zb] = i
ind, bools

(array([[[0., 4.],
         [1., 5.]],
 
        [[3., 7.],
         [2., 6.]]]),
 array([[False, False, False],
        [False,  True, False],
        [ True,  True, False],
        [ True, False, False],
        [False, False,  True],
        [False,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]]))

In [40]:
def get_normal(points):
    mid = np.mean(points, axis=0)
    u = points[0] - mid
    v = points[1] - mid
    return np.cross(u, v)

def get_normals(points: np.ndarray):
    bools = np.equal(points, np.max(points, axis=0))
    ret = []

    for i in range(3):
        test_points = a[bools[:, i] == True]
        normal = get_normal(test_points)
        ret.append(normal)
    
    return ret

get_normals(a)

[array([-0.60551273,  0.        , -0.        ]),
 array([ 0.       , -0.6065518, -0.       ]),
 array([-0.        ,  0.        , -0.24239079])]

[-0.5539627222056202,
 -0.5539627222056202,
 -0.5539627222056202,
 -0.5539627222056202]

In [46]:

def weighted_pts(pts_list, weight_num=10, std_inv=10):
    weights=np.exp(-(np.arange(weight_num)/std_inv)**2)[::-1] # wn
    print(weights)

weighted_pts([], 2, 1.0)

[0.36787944 1.        ]
